default_colours:
- '#f0991a'
- '#820000'
- '#32f01a'
- '#af1af0'
- '#070d0d'
- '#016795'
resolutions:
- 3840x2160
- 1920x1080
- 1300x1300
sub_title_presets:
- Higher scores indicate higher performance
- Lower scores indicate higher performance
- test
title_presets:
- CPU Scores
- GPU Scores
